/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.vcnet.storemodule.client.user_interfaces;

import java.awt.Dimension;
import java.awt.Point;
import lk.vcnet.storemodule.client.main.ClientMain;
import lk.vcnet.storemodule.client.main.LoggedUser;


/**
 *
 * @author user
 */
public class Welcome extends javax.swing.JFrame {

    private static Welcome instance;
    
    private Welcome() 
    {
        initComponents();
        setLocation(new Point(0, 0));
        setSize(ClientMain.getDisplaySize());
        if(!LoggedUser.getInstance().isLogged())
        {
           this.add(Login.getInstance());
        }
    }

    public static synchronized Welcome getInstance()
    {
        if(instance==null) instance=new Welcome();
        return instance;
    }
    
    public void disableMenuBar()
    {
        try {
            mnbr.getMenu(1).setEnabled(false);
        } catch (Exception e) {
        }
    }
    
    public void setUserMenu(String uname)
    {
        miuname.setText(uname);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnbr = new javax.swing.JMenuBar();
        miChngCtgry = new javax.swing.JMenu();
        miAdCtgry = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        miuname = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME");
        setPreferredSize(new java.awt.Dimension(1024, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        miChngCtgry.setText("Category");
        miChngCtgry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miChngCtgryMouseClicked(evt);
            }
        });

        miAdCtgry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        miAdCtgry.setText("Add Category");
        miChngCtgry.add(miAdCtgry);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setText("Change Category");
        miChngCtgry.add(jMenuItem9);

        mnbr.add(miChngCtgry);

        jMenu2.setText("Brand");

        jMenuItem10.setText("Add Brand");
        jMenu2.add(jMenuItem10);

        jMenuItem6.setText("Change Brand");
        jMenu2.add(jMenuItem6);

        mnbr.add(jMenu2);

        jMenu3.setText("Product");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });

        jMenuItem2.setText("Add Product");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem7.setText("Change Product");
        jMenu3.add(jMenuItem7);

        mnbr.add(jMenu3);

        jMenu4.setText("Inventory");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });

        jMenuItem14.setText("Add Inventory");
        jMenu4.add(jMenuItem14);

        jMenuItem8.setText("Change Inventory");
        jMenu4.add(jMenuItem8);

        mnbr.add(jMenu4);

        jMenu5.setText("Supplier");

        jMenuItem18.setText("Add Supplier");
        jMenu5.add(jMenuItem18);

        jMenu15.setText("Change Supplier");

        jMenuItem19.setText("Search");
        jMenu15.add(jMenuItem19);

        jMenuItem20.setText("Update");
        jMenu15.add(jMenuItem20);

        jMenuItem21.setText("Delete");
        jMenu15.add(jMenuItem21);

        jMenu5.add(jMenu15);

        mnbr.add(jMenu5);

        jMenu6.setText("Purchase Order");

        jMenuItem22.setText("Add Purchase Order");
        jMenu6.add(jMenuItem22);

        jMenu16.setText("Change Purchase Order");

        jMenuItem23.setText("Search");
        jMenu16.add(jMenuItem23);

        jMenuItem24.setText("Update");
        jMenu16.add(jMenuItem24);

        jMenuItem25.setText("Delete");
        jMenu16.add(jMenuItem25);

        jMenu6.add(jMenu16);

        mnbr.add(jMenu6);

        jMenu8.setText("Order ");

        jMenuItem1.setText("Order Product ");
        jMenu8.add(jMenuItem1);

        jMenu17.setText("Change Order");

        jMenuItem26.setText("Search");
        jMenu17.add(jMenuItem26);

        jMenuItem27.setText("Update");
        jMenu17.add(jMenuItem27);

        jMenuItem28.setText("Delete");
        jMenu17.add(jMenuItem28);

        jMenu8.add(jMenu17);

        mnbr.add(jMenu8);

        jMenu10.setText("Payment");

        jMenuItem29.setText("Add Payment");
        jMenu10.add(jMenuItem29);

        jMenu18.setText("Change Payment");

        jMenuItem30.setText("Search");
        jMenu18.add(jMenuItem30);

        jMenuItem31.setText("Update");
        jMenu18.add(jMenuItem31);

        jMenuItem32.setText("Delete");
        jMenu18.add(jMenuItem32);

        jMenu10.add(jMenu18);

        mnbr.add(jMenu10);

        miuname.setText("Username");

        jMenuItem33.setText("Logout");
        miuname.add(jMenuItem33);

        mnbr.add(miuname);

        setJMenuBar(mnbr);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
      //  new inventory().setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void miChngCtgryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miChngCtgryMouseClicked
       
    }//GEN-LAST:event_miChngCtgryMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       // new add_product().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setResizable(false);
    }//GEN-LAST:event_formWindowOpened

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem miAdCtgry;
    private javax.swing.JMenu miChngCtgry;
    private javax.swing.JMenu miuname;
    private javax.swing.JMenuBar mnbr;
    // End of variables declaration//GEN-END:variables
}
